// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package mcshimbin embeds the CUDA multicast suspend/resume interposer
// (mcshim.so) into the runsc binary, so that a GPU container can be given the
// interposer without its image having to carry it.
//
// The sources live in tools/mcshim; see its README.md for the protocol.
// runsc/boot materializes these bytes into a container's filesystem when
// --cuda-multicast-shim-source=EMBEDDED is set, and pkg/sentry/control/state_cuda*
// drives the interposer during checkpoint/restore.
package mcshimbin

import (
	_ "embed" // Necessary to use go:embed.
)

// The embedded file below is generated by a genrule in this package's BUILD
// file (from the //tools/mcshim cc_binary target), so it exists only in
// Bazel's output tree; non-Bazel tooling will report the embed pattern as
// unmatched. Same situation as //tools/ioctl_sniffer.
//
//go:embed mcshim.so
var interposer []byte

// Interposer returns the contents of the embedded interposer library
// (mcshim.so). Callers must not modify the returned slice.
func Interposer() []byte {
	return interposer
}
